spring:
  application:
    name: qk-parent

  datasource:
    url: jdbc:mysql://localhost:3306/db_qk
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      client-type: lettuce

# 配置MyBatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
        id-type: auto

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: hjh-java-ai
    region: cn-beijing